name: test

defaults:
  run:
    shell: bash -leo pipefail {0}

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-tests:
    runs-on: self-hosted
    strategy:
      matrix:
        destination: [
          'macOS', 
          'iOS Simulator,name=iPhone 16,OS=18.5', 
          'tvOS Simulator,name=Apple TV,OS=18.5', 
          'watchOS Simulator,name=Apple Watch Series 10 (42mm),OS=11.5'
        ]
        xcode: [
          '16.4',
          '26.0.1',
        ]
    steps:
      - uses: actions/checkout@v4
      - name: Install Gems
        run: bundle install
      - name: Run tests
        env:
          DESTINATION: platform=${{ matrix.destination }}
          XCODE_VERSION: ${{ matrix.xcode }}
        run: bundle exec fastlane test_ci
